### ISSUE TITLE
Not able to run on debug mode

### ISSUE THREAD

**Issue by cpomp** [mp911de/debuggable-selenide#1]
This looks very interesting, sadly I wasn't able to run the project in debug mode
I imported the project and followed the instructions "start the class biz.paluch.testing.acceptance.StandaloneLauncher as JUnit test"
## That produced the following exception

Scenario: 
Given I'm on http://www.paluch.biz
When I click Blog
Then the URL ends with /blog.html
Given I'm on http://www.paluch.biz/blog.html
# this one will fail since there are no 99 entries

When I click entry no 99 (FAILED)
(java.awt.IllegalComponentStateException: contentPane cannot be set to null.)

java.awt.IllegalComponentStateException: contentPane cannot be set to null.
    at javax.swing.JRootPane.setContentPane(JRootPane.java:621)
    at javax.swing.JDialog.setContentPane(JDialog.java:1046)
    at biz.paluch.testing.acceptance.debug.StoryExceptionDialog.initialize(StoryExceptionDialog.java:67)
    at biz.paluch.testing.acceptance.debug.StoryExceptionDialog.open(StoryExceptionDialog.java:204)
    at biz.paluch.testing.acceptance.debug.DebugInvoationInterceptor.invoke(DebugInvoationInterceptor.java:47)
    (reflection-invoke)
    at org.jbehave.core.steps.StepCreator$ParametrisedStep.perform(StepCreator.java:598)
    at org.jbehave.core.embedder.PerformableTree$FineSoFar.run(PerformableTree.java:315)
## ...

I then tried to initialize all the swing components in the StoryExceptionDialog() ctor
This got me further but I then again get stuck \@
.StoryExceptionDialog.open(StoryExceptionDialog.java:216)
  dialog.setVisible(true);

This bring is an empty dialog. I guess the gridlayout w all the components should have been picked up from StoryExceptionDialog.form. However, it doesn't seem to be doing so

I see that namespace for that xml is from "intellij". Is this an intellij only feature? What I'm I doing wrong?

I appreciate your help in advance

**Comment by mp911de** [comment]
I apologize for the inconvenience. I discovered myself that running the UI only works with IntelliJ IDEA and Eclipse kills the GUI part. You have two options:
1. Execute the project using Maven: `mvn clean install exec:java -Dexec.mainClass=biz.paluch.testing.acceptance.StandaloneLauncher` in your console
2. This is a bit more tricky: Build the project using `mvn clean install`, create a run configuration for class `biz.paluch.testing.acceptance.StandaloneLauncher`, edit the classpath settings and add `target/debuggable-selenide-1.0-SNAPSHOT.jar` as first class path entry (right before the Eclipse-Autogenerated classpath).

I pushed updated code (with more drivers and mvn exec plugin support) a couple minutes ago.

Please let me know whether any approach worked for you. I guess I will have to create real UI code instead of relying on IntelliJ.

**Comment by cpomp** [comment]
Thx I'm now able to run it w the new instructions and also run in debug mode
When making changes is a little painful because I have to run "mvn clean install" for the jar to be updated before the changes will me picked up

**Comment by mp911de** [comment]
I checked in the generated GUI code. Now it should work like a charm.

**Comment by cpomp** [comment]
You are right, it does work like a charm :)
FYI, the running instructions are now outdated. Now I can just run w the original instructions of running "biz.paluch.testing.acceptance.StandaloneLauncher" as JUnit. Thx again!

When I ran in Eclipse as maven
$ mvn clean install exec:java -Dexec.mainClass=biz.paluch.testing.acceptance.StandaloneLauncher

I get a "java.awt.HeadlessException". From outpout:
(paluch.biz.blog.story)
Scenario: 
Given I'm on http://www.paluch.biz
When I click Blog
Then the URL ends with /blog.html
Given I'm on http://www.paluch.biz/blog.html

# this one will fail since there are no 99 entries

When I click entry no 99 (FAILED)
(java.awt.HeadlessException)

java.awt.HeadlessException
    at java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:207)
    at java.awt.Window.<init>(Window.java:536)
    at java.awt.Frame.<init>(Frame.java:420)
    at java.awt.Frame.<init>(Frame.java:385)
    at javax.swing.SwingUtilities$SharedOwnerFrame.<init>(SwingUtilities.java:1758)
    at javax.swing.SwingUtilities.getSharedOwnerFrame(SwingUtilities.java:1833)
    at javax.swing.JDialog.<init>(JDialog.java:272)
    at javax.swing.JDialog.<init>(JDialog.java:206)
    at javax.swing.JDialog.<init>(JDialog.java:154)
    at biz.paluch.testing.acceptance.debug.StoryExceptionDialog.<init>(StoryExceptionDialog.java:59)
    at biz.paluch.testing.acceptance.debug.StoryExceptionDialog.open(StoryExceptionDialog.java:225)
    at biz.paluch.testing.acceptance.debug.DebugInvoationInterceptor.invoke(DebugInvoationInterceptor.java:46)
    (reflection-invoke)
    at org.jbehave.core.steps.StepCreator$ParametrisedStep.perform(StepCreator.java:598)
    at org.jbehave.core.embedder.PerformableTree$FineSoFar.run(PerformableTree.java:315)
...

**Comment by mp911de** [comment]
Guess because of java.awt.headless=true is set in the pom. try with -Djava.awt.headless=false, I'll add it also to the docs
